#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := receive_ir_message.cpp

# header files in this project
HEADERS := receive_ir_message.hpp

# other places to look for files for this project
SEARCH  := 
SERIAL_PORT:= COM3

# set BMPTK to the next higher directory and defer to the Makefile.due
BMPTK := $(BMPTK)../
include $(BMPTK)Makefile.due
