.PHONY: clean All

All:
	@echo "----------Building project:[ the_game -  ]----------"
	@cd "the_game" && "$(MAKE)" -f  "the_game.mk"
clean:
	@echo "----------Cleaning project:[ the_game -  ]----------"
	@cd "the_game" && "$(MAKE)" -f  "the_game.mk" clean
