.PHONY: clean All

All:
	@echo "----------Building project:[ receive_signal - Debug ]----------"
	@cd "receive_signal" && "$(MAKE)" -f  "receive_signal.mk"
clean:
	@echo "----------Cleaning project:[ receive_signal - Debug ]----------"
	@cd "receive_signal" && "$(MAKE)" -f  "receive_signal.mk" clean
