#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

SERIAL_PORT ?= COM3

# source files in this project (main.cpp is automatically assumed)
SOURCES :=

# header files in this project
HEADERS := ir_receiver_classes.hpp application_logic_classes.hpp test_class.hpp entity_classes.hpp

# other places to look for files for this project
SEARCH  := 

# set BMPTK to the next higher directory and defer to the Makefile.due
BMPTK := $(BMPTK)../
include $(BMPTK)Makefile.due
